### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by Tifo22** [jphuang/shopping#1]
这么长时间过去了，不知道楼主还在不在。。。请问代码是完整的吗

**Comment by jphuang** [comment]
> 这么长时间过去了，不知道楼主还在不在。。。请问代码是完整的吗

完整的，有什么问题吗

**Comment by Tifo22** [comment]
> > 这么长时间过去了，不知道楼主还在不在。。。请问代码是完整的吗
> 
> 完整的，有什么问题吗

哇，没想到您回的这么快。就是我发现代码里有一些定义的类并没用上，有些函数没有函数体，我用eclipse(jdk已经改成1.6了)导入项目以后发现并没有run as application的选项，所以感觉可能有些问题

**Comment by jphuang** [comment]
> > > 这么长时间过去了，不知道楼主还在不在。。。请问代码是完整的吗
> > 
> > 
> > 完整的，有什么问题吗
> 
> 哇，没想到您回的这么快。就是我发现代码里有一些定义的类并没用上，有些函数没有函数体，我用eclipse(jdk已经改成1.6了)导入项目以后发现并没有run as application的选项，所以感觉可能有些问题


不好意思，上班比较忙，没有空看，代码是完整的，函数没有函数体可能那时一些接口，你要找到 ShopConfig  去运行项目，他本质就是一个java的main方法

**Comment by Serendipitychen** [comment]
楼主在吗？ 我的显示运行成功 但是网页打开的话 返回500

**Comment by zZLOVEZz1314** [comment]
楼主在吗，我没找到run as java application，IDEA2021

**Comment by LLLi1z** [comment]
楼主在吗，我没找到Debug as java application，请问在哪里选择啊，IDEA2021
